package games.sautreiber;

import games.dialogeGUIs.GameSettingsDialog;


public class SauTreiberSettingsDialog extends GameSettingsDialog {
	/**
	 * SerialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	private SauTreiber sau;

	public SauTreiberSettingsDialog(SauTreiber sau) {
		super(sau);
		this.sau = sau;
		initGUI();
	}

	private void initGUI(){
		setMaxRunden(5000);
		rundenzahlSlider.setPaintLabels(false);
		rundenzahlSlider.setMinimum(500);
		rundenzahlSlider.setValue(sau.numOfRounds);
		rundenzahlSlider.setMinorTickSpacing(500);
		rundenzahlSlider.setMajorTickSpacing(1500);
		rundenzahlSlider.setLabelTable(rundenzahlSlider.createStandardLabels(1500, 500));
		rundenzahlSlider.setPaintLabels(true);
		propertiesToSettings();
	}

	@Override
	public void speichern(){
		sau.numOfRounds = rundenzahlSlider.getValue();
		super.speichern();
	}
}
