package games.sautreiber;

import games.dialogeGUIs.GameSettingsDialog;

import java.awt.GridLayout;

import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.SwingConstants;


public class SauTreiberSettingsDialog extends GameSettingsDialog {
	/**
	 * SerialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	private SauTreiber sau;

	private JLabel rundenzahlLabel;

	private JSlider rundenzahlSlider;
	public SauTreiberSettingsDialog(SauTreiber sau) {
		super(sau);
		this.sau = sau;
		initGUI();
	}

	private void initGUI(){
		settingsPanel.setLayout(new GridLayout(1,2));
		rundenzahlLabel = new JLabel("Siegpunktzahl (x100)");
		settingsPanel.add(rundenzahlLabel);
		rundenzahlSlider = new JSlider(SwingConstants.HORIZONTAL,5,50,sau.numOfRounds/100);
		rundenzahlSlider.setMajorTickSpacing(5);
		rundenzahlSlider.setMinorTickSpacing(5);
		rundenzahlSlider.setSnapToTicks(true);
		rundenzahlSlider.setPaintTicks(true);
		rundenzahlSlider.setPaintLabels(true);
		settingsPanel.add(rundenzahlSlider);
	}

	@Override
	public void speichern(){
		sau.numOfRounds = rundenzahlSlider.getValue()*100;
		super.speichern();
	}
}
