package gui;

import javax.swing.JPanel;

import start.X;

public class Anzeige extends JPanel {

	/**
	 * serialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 4973655170808865942L;

	/**
	 * In dieser Methode werden abschließende Arbeiten durchgeführt, bevor die TotenAnzeige
	 * entfernt (und durch eine neue ersetzt wird)
	 */
	public X instance;
	public Anzeige(){
		this.instance = X.getInstance();
		this.setOpaque(false);
	}

	public void destroy(){

	}

	public void nowVisible(){

	}

}
