package gui;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;

public class AnzeigeDialog extends Anzeige {
	/**
	 * SerialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 7568357329432251035L;
	public JPanel dialogPane;
	public AnzeigeDialog(){
		initGUI();
	}
	
	private void initGUI() {
		this.setLayout(new BorderLayout());
		addDialogPaneCentered();
	}
	
	private void addDialogPaneCentered() {
		dialogPane = new JPanel();
		addDialogPaneToDummyPanel();
		dialogPane.setLayout(new FlowLayout());
		dialogPane.setBackground(new Color(100,100,255));
		dialogPane.setBorder(BorderFactory.createEtchedBorder(BevelBorder.RAISED));
		
	}

	private void addDialogPaneToDummyPanel() {
		GridBagLayout gbl      = new GridBagLayout();
		GridBagConstraints gbc = new GridBagConstraints();
		gbc.anchor             = GridBagConstraints.CENTER;
		JPanel dummyPanel = new JPanel(gbl);
		dummyPanel.setOpaque(false);
		gbl.setConstraints(dialogPane,gbc);
		dummyPanel.add(dialogPane);
		this.add(dummyPanel,BorderLayout.CENTER);
	}

	public void pack(){
		dialogPane.setPreferredSize(dialogPane.getLayout().preferredLayoutSize(dialogPane));
	}
}
