** Installation

#+BEGIN_EXAMPLE
  git clone https://github.com/iimog/x-party-game
#+END_EXAMPLE

** Game Idea

Multiple players or teams play a match against each other. In which they compete in various mini games.
The winner of each mini game earns points for the final rating.
The mini games are intended to be short (a couple of minutes each) and fun.
There are mini games that are played with the computer and others that are played in the real world. 

** Language
Currently the game is completely in German.
An english translation is planned but not yet in progress.
** A general note

I started developing this game years ago to get some experience in java programming.
This game more or less evolved from my very first HelloWorld.java
As I was learning, I adapted the code. 
Throughout the years I changed code, documentation, patterns, libraries, IDEs, version control systems, etc.
Therefore it is a patchwork that contains code from various levels of experience.
Unfortunately neither me nor my team members are experts in licensing.
As we rely heavily on content provided by others I will add an appropriate LICENSE as soon as I have figured things out.
The game is designed to be customizable and extensible by the user.
We like the game idea a lot and think we have created a nice implementation.
However the patchwork nature of the project leads to some limitations, 
to avoid them a complete redesign and re-implementation from scratch would be required.
Unfortunately I don't have time to do that. 
I will fix remaining bugs, include new games and content sporadically and participate in discussions.

** Version

This is version 0.9
It still contains some bugs and inconsistencies.
As soon as they are fixed and an appropriate License is found version 1.0 will be released.
Following that new releases will increase the minor version number.
The major version number 2 is reserved for a completely redesigned version (in the far future or if someone jumps in)

This game contains sound effects obtained from https://www.zapsplat.com (see licenses/LICENSE for details).

** Contributing

Contributions of any kind are welcome. Please see the [[https://iimog.org/X/][website]] or contact me directly.

** Dependencies

- Java (>=6)

** Usage
Start via the .jar file
#+BEGIN_EXAMPLE
  java -jar X.jar
#+END_EXAMPLE

or via the java class
#+BEGIN_EXAMPLE
  java start/X
#+END_EXAMPLE

** Contact
If you have any questions or encounter problems or potential bugs, don't
hesitate to contact us. Either report [[https://github.com/iimog/x-party-game/issues][issues]] on github or write an email to:

- Markus Ankenbrand - markus@ankenbrand.me

** Credits
- Markus Ankenbrand (source code)
- Tobias Ankenbrand (content, games)
- Moritz Ankenbrand (content, games)



#+TITLE: x-party-game README
#+AUTHOR: Markus Ankenbrand
#+EMAIL: markus@ankenbrand.me
#+LANGUAGE: de
#+OPTIONS: ^:nil date:nil H:2
#+LaTeX_CLASS: scrartcl
#+LaTeX_CLASS_OPTIONS: [a4paper,12pt,headings=small]
#+LaTeX_HEADER: \setlength{\parindent}{0pt}
#+LaTeX_HEADER: \setlength{\parskip}{1.5ex}
#+LATEX_HEADER: \renewcommand{\familydefault}{\sfdefault}


  #+ATTR_HTML: title="Join the chat at https://gitter.im/iimog/x-party-game"
  [[https://gitter.im/iimog/x-party-game?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge][file:https://badges.gitter.im/Join%20Chat.svg]]
