package gui.menu;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

import util.SpielListen;


public class GameChoosePanel extends JPanel {

	/**
	 * serialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = -1254976229486231704L;

	public int numOfGames;
	public ArrayList<JLabel> labelList = new ArrayList<JLabel>(30);
	public ArrayList<JComboBox> comboBoxList = new ArrayList<JComboBox>(30);
	public ArrayList<Integer> gameList = new ArrayList<Integer>(30);
	public StartMatch startMatch;

	public GameChoosePanel(StartMatch startMatch){
		List<String> erwuenschteSpiele = SpielListen.getGameNames(startMatch.getErwuenschteSpiele());
		this.startMatch = startMatch;
		this.numOfGames = startMatch.getPrefNumOfGames();
		this.gameList = startMatch.getGameList();
		
		for(int i=0; i<numOfGames; i++){
			JLabel lab = new JLabel("Spiel "+(i+1));
			lab.setForeground(Color.white);
			lab.setHorizontalAlignment(SwingConstants.RIGHT);
			labelList.add(lab);
			JComboBox combo = new JComboBox();
			combo.setForeground(Color.WHITE);
			combo.setBackground(Color.DARK_GRAY);
			ComboBoxModel model = new DefaultComboBoxModel(erwuenschteSpiele.toArray());
			model.setSelectedItem(SpielListen.getGameName(gameList.get(i)));
			combo.setModel(model);
			combo.setEditable(false);
			combo.addActionListener(new ActionListener(){
				public void actionPerformed(ActionEvent evt){
					updateGameList();
				}
			});
			comboBoxList.add(combo);
		}
		initGUI();
	}

	private void initGUI(){
		this.setOpaque(false);
		this.setLayout(new GridLayout(numOfGames,2));
		for(int i=0; i<numOfGames; i++){
			this.add(labelList.get(i));
			GridBagLayout gbl      = new GridBagLayout();
			GridBagConstraints gbc = new GridBagConstraints();
			gbc.anchor             = GridBagConstraints.CENTER;
			JPanel panel = new JPanel(gbl);
			panel.setOpaque(false);
			gbl.setConstraints(comboBoxList.get(i),gbc);
			panel.add(comboBoxList.get(i));
			this.add(panel);
		}
	}

	private void updateGameList(){
		for(int i = 0; i<numOfGames; i++){
			String gameName = (String)comboBoxList.get(i).getSelectedItem();
			gameList.set(i, SpielListen.getGameIDbyName(gameName));
		}
	}
}
