package games.guess;

import games.Modus;
import games.dialogeGUIs.GameSettingsDialog;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.SwingConstants;


public class GuessSettingsDialog extends GameSettingsDialog {
	/**
	 * SerialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	private Guess guess;

	private JLabel rundenzahlLabel;

	private JSlider rundenzahlSlider;

	private JLabel toleranzLabel;

	private JSlider toleranzSlider;

	private JLabel toleranzOnLabel;

	private JCheckBox toleranzCheckBox;
	public GuessSettingsDialog(Guess guess) {
		super(guess);
		this.guess = guess;
		initGUI();
	}

	private void initGUI(){
		settingsPanel.setLayout(new GridLayout(3,2));
		rundenzahlLabel = new JLabel("Siegpunktzahl");
		settingsPanel.add(rundenzahlLabel);
		rundenzahlSlider = new JSlider(SwingConstants.HORIZONTAL,1,10,guess.numOfRounds);
		rundenzahlSlider.setMajorTickSpacing(1);
		rundenzahlSlider.setMinorTickSpacing(1);
		rundenzahlSlider.setSnapToTicks(true);
		rundenzahlSlider.setPaintTicks(true);
		rundenzahlSlider.setPaintLabels(true);
		settingsPanel.add(rundenzahlSlider);
		{
			toleranzLabel = new JLabel();
			settingsPanel.add(toleranzLabel);
			toleranzLabel.setText("Toleranz in %");
		}
		{
			toleranzSlider = new JSlider(SwingConstants.HORIZONTAL,0,200,10);
			toleranzSlider.setValue((int) (guess.toleranz*100));
			toleranzSlider.setMajorTickSpacing(25);
			toleranzSlider.setMinorTickSpacing(5);
			toleranzSlider.setSnapToTicks(true);
			toleranzSlider.setPaintTicks(true);
			toleranzSlider.setPaintLabels(true);
			toleranzSlider.setEnabled(guess.toleranzOn);
			settingsPanel.add(toleranzSlider);
		}
		{
			toleranzOnLabel = new JLabel();
			settingsPanel.add(toleranzOnLabel);
			toleranzOnLabel.setText("Toleranz anschalten");
		}
		{
			toleranzCheckBox = new JCheckBox();
			toleranzCheckBox.setSelected(guess.toleranzOn);
			settingsPanel.add(toleranzCheckBox);
			toleranzCheckBox.setText("Toleranz");
			if(guess.modus == Modus.SOLO)toleranzCheckBox.setEnabled(false);
			toleranzCheckBox.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent evt) {
					toleranzCheckBoxActionPerformed(evt);
				}
			});
		}
	}

	@Override
	public void speichern(){
		guess.numOfRounds = rundenzahlSlider.getValue();
		guess.toleranzOn = toleranzCheckBox.isSelected();
		guess.toleranz = ((double)toleranzSlider.getValue())/100;
		super.speichern();
	}

	private void toleranzCheckBoxActionPerformed(ActionEvent evt) {
		toleranzSlider.setEnabled(toleranzCheckBox.isSelected());
	}
}
