package games.bad6;

import games.dialogeGUIs.GameSettingsDialog;

import java.awt.GridLayout;

import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.SwingConstants;


public class Bad6SettingsDialog extends GameSettingsDialog {

	/**
	 * SerialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	private Bad6 boese;

	private JLabel rundenzahlLabel;

	private JSlider rundenzahlSlider;
	public Bad6SettingsDialog(Bad6 bad) {
		super(bad);
		boese = bad;
		initGUI();
	}

	private void initGUI(){
		settingsPanel.setLayout(new GridLayout(1,2));
		rundenzahlLabel = new JLabel("Siegpunktzahl");
		settingsPanel.add(rundenzahlLabel);
		rundenzahlSlider = new JSlider(SwingConstants.HORIZONTAL,10,100,boese.numOfRounds);
		rundenzahlSlider.setMajorTickSpacing(10);
		rundenzahlSlider.setMinorTickSpacing(10);
		rundenzahlSlider.setSnapToTicks(true);
		rundenzahlSlider.setPaintTicks(true);
		rundenzahlSlider.setPaintLabels(true);
		settingsPanel.add(rundenzahlSlider);
	}

	@Override
	public void speichern(){
		boese.numOfRounds = rundenzahlSlider.getValue();
		super.speichern();
	}
}
