package games.bad6;

import games.dialogeGUIs.GameSettingsDialog;


public class Bad6SettingsDialog extends GameSettingsDialog {

	/**
	 * SerialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	private Bad6 boese;

	public Bad6SettingsDialog(Bad6 bad) {
		super(bad);
		boese = bad;
		initGUI();
	}

	private void initGUI(){
		setMaxRunden(100);
		rundenzahlSlider.setPaintLabels(false);
		rundenzahlSlider.setLabelTable(rundenzahlSlider.createStandardLabels(30, 10));
		rundenzahlSlider.setMinimum(10);
		rundenzahlSlider.setValue(boese.numOfRounds);
		rundenzahlSlider.setMinorTickSpacing(10);
		rundenzahlSlider.setMajorTickSpacing(30);
		rundenzahlSlider.setPaintLabels(true);
		propertiesToSettings();
	}

	@Override
	public void speichern(){
		boese.numOfRounds = rundenzahlSlider.getValue();
		super.speichern();
	}
}
