package games.ghosts;

import games.Game;
import games.dialogeGUIs.GameSettingsDialog;


public class GhostsSettingsDialog extends GameSettingsDialog {
	/**
	 * SerialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	private Game ghosts;

	public GhostsSettingsDialog(Game ghosts) {
		super(ghosts);
		this.ghosts = ghosts;
		setMaxRunden(5);
		rundenzahlSlider.setValue(ghosts.numOfRounds);
	}

	@Override
	public void speichern(){
		ghosts.numOfRounds = rundenzahlSlider.getValue();
		super.speichern();
	}
}
