package gui.components;

import java.awt.Dimension;

import javax.swing.ImageIcon;

public class JButtonIcon extends DefaultButton {
	/**
	 * Serial Version UID generated by Eclipse
	 */
	private static final long serialVersionUID = -5447642185291377872L;

	ImageIcon icon;

	private ImageIcon disabledIcon;
	public JButtonIcon(String icon, String alternativ){
		super();
		try{
			this.icon = new ImageIcon(getToolkit().getImage(getClass().getResource(icon)));
			this.setIcon(this.icon);
			this.setOpaque(false);
		}
		catch(Exception e){
			this.setText(alternativ);
		}
		if(this.icon.getIconHeight()<0 || this.icon.getIconWidth()<0){
			this.icon = null;
			this.setText(alternativ);
		}
	}
	@Override
	public Dimension getPreferredSize(){
		if(icon!=null){
			return new Dimension(icon.getIconWidth(),icon.getIconHeight());
		}
		else {
			return super.getPreferredSize();
		}
	}
	
	public void changeIcon(String icon, String alternativ){
		changeIcon(icon, alternativ, false);
	}
	
	public void changeIcon(String icon, String alternativ, boolean alsoDisabledIcon){
		try{
			this.icon = new ImageIcon(getToolkit().getImage(getClass().getResource(icon)));
			this.setIcon(this.icon);
			if(alsoDisabledIcon){
				setDisabledIcon(icon);
			}
		}
		catch(Exception e){
			this.setText(alternativ);
		}
		if(this.icon.getIconHeight()<0 || this.icon.getIconWidth()<0){
			this.icon = null;
			this.setText(alternativ);
		}
	}
	
	public void setDisabledIcon(String icon){
		try{
			disabledIcon = new ImageIcon(getToolkit().getImage(getClass().getResource(icon)));
			this.setDisabledIcon(disabledIcon);
		}
		catch(Exception e){
			System.out.println("Fehler beim setzen des disabledIcons: "+disabledIcon);
		}
	}
}
