package games.dialogeGUIs;
import games.Game;
import gui.AnzeigeDialog;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JPanel;



/**
 * This code was edited or generated using CloudGarden's Jigloo
 * SWT/Swing GUI Builder, which is free for non-commercial
 * use. If Jigloo is being used commercially (ie, by a corporation,
 * company or business for any purpose whatever) then you
 * should purchase a license for each developer using Jigloo.
 * Please visit www.cloudgarden.com for details.
 * Use of Jigloo implies acceptance of these licensing terms.
 * A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
 * THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
 * LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
 */
public class GameSettingsDialog extends AnzeigeDialog {

	/**
	 * serialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = -1171647157012743374L;
	private JPanel buttonPanel;
	private JButton speichernButton;
	private JButton verwerfenButton;
	public JPanel settingsPanel;
	public Game myGame;

	public GameSettingsDialog(Game g){
		myGame = g;
		initGUI();
	}

	private void initGUI() {
		try {
			BorderLayout thisLayout = new BorderLayout();
			dialogPane.setLayout(thisLayout);
			{
				settingsPanel = new JPanel();
				dialogPane.add(settingsPanel, BorderLayout.CENTER);
			}
			{
				buttonPanel = new JPanel();
				FlowLayout buttonPanelLayout = new FlowLayout();
				dialogPane.add(buttonPanel, BorderLayout.SOUTH);
				buttonPanel.setLayout(buttonPanelLayout);
				{
					speichernButton = new JButton();
					buttonPanel.add(speichernButton);
					speichernButton.setText("Speichern");
					speichernButton.addActionListener(new ActionListener() {
						public void actionPerformed(ActionEvent evt) {
							speichern();
						}
					});
				}
				{
					verwerfenButton = new JButton();
					buttonPanel.add(verwerfenButton);
					verwerfenButton.setText("Verwerfen");
					verwerfenButton.addActionListener(new ActionListener() {
						public void actionPerformed(ActionEvent evt) {
							verwerfenButtonActionPerformed(evt);
						}
					});
				}
			}
		} catch(Exception e) {
			e.printStackTrace();
		}
	}

	public void speichern() {
		myGame.settingsChanged();
		instance.closeDialog();
	}

	private void verwerfenButtonActionPerformed(ActionEvent evt) {
		instance.closeDialog();
	}

}
