package ablauf;

import gui.Anzeige;
import gui.menu.HauptMenu;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

import player.Player;



public class Siegerehrung extends Anzeige {

	/**
	 * SerialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = -8781455635836415785L;
	private Player sieger;
	private JPanel mainPanel;
	private JPanel buttonPanel;
	private JButton okButton;
	public Siegerehrung(Player sieger){
		this.sieger = sieger;
		initGUI();
	}
	private void initGUI(){
		setLayout(new BorderLayout());
		mainPanel = new JPanel();
		mainPanel.setOpaque(false);
		mainPanel.setLayout(new BorderLayout());
		add(mainPanel, BorderLayout.CENTER);
		{
			JLabel ueberschrift = new JLabel("Das Match geht an...");
			ueberschrift.setFont(new Font("Comic Sans MS",1,40));
			ueberschrift.setForeground(Color.WHITE);
			mainPanel.add(ueberschrift,BorderLayout.NORTH);
		}
		{
			JLabel siegerLabel = new JLabel(sieger.name);
			siegerLabel.setFont(new Font("Comic Sans MS",0,150));
			siegerLabel.setHorizontalAlignment(JLabel.CENTER);
			siegerLabel.setForeground(sieger.farbe);
			mainPanel.add(siegerLabel,BorderLayout.CENTER);
		}
		{
			buttonPanel = new JPanel();
			buttonPanel.setOpaque(false);
			buttonPanel.setLayout(new FlowLayout());
			mainPanel.add(buttonPanel, BorderLayout.SOUTH);
			{
				okButton = new JButton("OK");
				buttonPanel.add(okButton);
				okButton.addActionListener(new ActionListener(){
					public void actionPerformed(ActionEvent evt){
						okButtonActionPerformed();
					}
				});
			}
		}
	}
	protected void okButtonActionPerformed() {
		instance.changeAnzeige(new HauptMenu());
	}
	public void nowVisible(){
		instance.changeBackground("media/sieger/girls.jpg");
		if(!sieger.male || sieger.name.equals("Frauen")){
			instance.changeBackground("media/sieger/sexyman.jpg");
		}
	}
}
