package games.nonPC;

import games.Modus;
import player.Player;

public class ApfelImWasser extends StandardNonPC {
	/**
	 * SerialVersioUID generated by Eclipse
	 */
	private static final long serialVersionUID = -218387602330979064L;
	public static String gameName = "Apfel im Wasser";
	public static String getGameName(){
		return gameName;
	}
	public static String shortInfo = "Hole einen Apfel nur mit deinem Mund aus einer Schüssel Wasser/Sangria!";

	public static int defaultNumOfRounds = 5;
	public ApfelImWasser(Player[] player, Modus modus) {
		super(gameName, player, defaultNumOfRounds, modus);
	}
	@Override
	public String getShortInfo() {
		return shortInfo;
	}
	@Override
	public void nowVisible(){
		instance.changeBackground("media/nonPC/apfelwasser/apfel.jpg");
	}
}
