package games.nonPC;

import games.Modus;
import player.Player;
import util.SpielListen;

public class Eisprung extends StandardNonPC {
	/**
	 * SerialVersioUID generated by Eclipse
	 */
	private static final long serialVersionUID = -218387602330979064L;
	public static String gameName = "Eisprung";
	public static String getGameName(){
		return gameName;
	}
	public static String shortInfo = "Wer bekommt das Ei unter Kontrolle?";
	private static final int GAME_ID = SpielListen.EISPRUNG;
	public int getGameID(){
		return GAME_ID;
	}
	public static int defaultNumOfRounds = 5;

	public Eisprung(Player[] player, Modus modus) {
		super(gameName, player, defaultNumOfRounds, modus);
	}

	@Override
	public String getShortInfo() {
		return shortInfo;
	}

	@Override
	public void nowVisible() {
		instance.changeBackground("media/nonPC/eisprung/ei.jpg");
	}
}
