package games.nonPC;

import games.Modus;
import player.Player;
import util.SpielListen;

public class KrugHalten extends StandardNonPC {

	/**
	 * SerialVersioUID generated by Eclipse
	 */
	private static final long serialVersionUID = -218387602330979064L;
	public static String gameName = "Krughalten";
	public static String getGameName(){
		return gameName;
	}
	public static String shortInfo = "Wer schafft es länger einen halb gefüllten" +
	" Maßkrug am ausgestreckten Arm zu halten.";
	private static final int GAME_ID = SpielListen.KRUG;
	public int getGameID(){
		return GAME_ID;
	}
	public static int defaultNumOfRounds = 3;
	public KrugHalten(Player[] player, Modus modus) {
		super(gameName, player, defaultNumOfRounds, modus);
	}
	@Override
	public String getShortInfo() {
		return shortInfo;
	}
	@Override
	public void nowVisible(){
		instance.changeBackground("media/nonPC/krughalten/09a.jpg");
	}

}
