package games.nonPC;

import games.Modus;
import player.Player;
import util.SpielListen;

public class MuenzWurf extends StandardNonPC {

	/**
	 * SerialVersioUID generated by Eclipse
	 */
	private static final long serialVersionUID = -218387602330979064L;
	public static String gameName = "Münzwurf";
	public static String getGameName(){
		return gameName;
	}
	public static String shortInfo = "Schnackel die Münze ins Glas.";
	private static final int GAME_ID = SpielListen.MUENZWURF;
	public int getGameID(){
		return GAME_ID;
	}
	public static int defaultNumOfRounds = 6;
	public MuenzWurf(Player[] player, Modus modus) {
		super(gameName, player, defaultNumOfRounds, modus);
	}
	@Override
	public String getShortInfo() {
		return shortInfo;
	}
	@Override
	public void nowVisible(){
		instance.changeBackground("media/nonPC/münzwurf/2euro.jpg");
	}
}
