package games.nonPC;

import games.Modus;
import player.Player;
import util.SpielListen;

public class Muenzschnipsen extends StandardNonPC {

	/**
	 * SerialVersioUID generated by Eclipse
	 */
	private static final long serialVersionUID = -218387602330979064L;
	public static String gameName = "Münzschnipsen";
	public static String getGameName(){
		return gameName;
	}
	public static String shortInfo = "Ein fußballähnliches Spiel, das mit Münzen auf dem Tisch gespielt wird.";
	private static final int GAME_ID = SpielListen.MUENZSCHNIPP;
	public int getGameID(){
		return GAME_ID;
	}
	public static int defaultNumOfRounds = 3;
	public Muenzschnipsen(Player[] player, Modus modus) {
		super(gameName, player, defaultNumOfRounds, modus);
	}
	@Override
	public String getShortInfo() {
		return shortInfo;
	}
	@Override
	public void nowVisible(){
		instance.changeBackground("media/nonPC/münzschnippen/stadion.jpg");
	}
}
