package games.nonPC;

import games.Modus;
import player.Player;
import util.SpielListen;

public class MundFangen extends StandardNonPC {
	/**
	 * SerialVersioUID generated by Eclipse
	 */
	private static final long serialVersionUID = -218387602330979064L;
	public static String gameName = "Mundfangen";
	public static String getGameName(){
		return gameName;
	}
	public static String shortInfo = "Es geht darum Gummibären (oder Erdnüsse) mit dem Mund aufzufangen \n" +
	"Geworfen wird nacheinander, wenn ein Team fängt und das andere nicht bekommt es einen Punkt";
	private static final int GAME_ID = SpielListen.MUNDFANG;
	public int getGameID(){
		return GAME_ID;
	}
	public static int defaultNumOfRounds = 8;
	public MundFangen(Player[] player, Modus modus) {
		super(gameName, player, defaultNumOfRounds, modus);
	}
	@Override
	public String getShortInfo() {
		return shortInfo;
	}
	@Override
	public void nowVisible(){
		instance.changeBackground("media/nonPC/mundfangen/Gummibär.jpg");
	}
}
