package games.nonPC;

import games.dialogeGUIs.GameSettingsDialog;

import java.awt.GridLayout;

import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.SwingConstants;


public class StandardSettingsDialog extends GameSettingsDialog {
	/**
	 * SerialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	private StandardNonPC nonPC;

	private JLabel rundenzahlLabel;

	private JSlider rundenzahlSlider;
	public StandardSettingsDialog(StandardNonPC nonPC) {
		super(nonPC);
		this.nonPC = nonPC;
		initGUI();
	}

	private void initGUI(){
		settingsPanel.setLayout(new GridLayout(1,2));
		rundenzahlLabel = new JLabel("Siegpunktzahl");
		settingsPanel.add(rundenzahlLabel);
		rundenzahlSlider = new JSlider(SwingConstants.HORIZONTAL,1,10,nonPC.numOfRounds);
		rundenzahlSlider.setMajorTickSpacing(1);
		rundenzahlSlider.setMinorTickSpacing(1);
		rundenzahlSlider.setSnapToTicks(true);
		rundenzahlSlider.setPaintTicks(true);
		rundenzahlSlider.setPaintLabels(true);
		settingsPanel.add(rundenzahlSlider);
	}

	@Override
	public void speichern(){
		nonPC.numOfRounds = rundenzahlSlider.getValue();
		super.speichern();
	}
}
