package games.nonPC;

import games.Modus;
import player.Player;
import util.SpielListen;

public class Weitergeben extends StandardNonPC {
	/**
	 * SerialVersioUID generated by Eclipse
	 */
	private static final long serialVersionUID = -218387602330979064L;
	public static String gameName = "Weitergeben";
	public static String getGameName(){
		return gameName;
	}
	public static String shortInfo = "Gib eine Erbse, über im Mund gehaltene Löffel, einmal im Kreis!";
	private static final int GAME_ID = SpielListen.WEITERGEBEN;
	public int getGameID(){
		return GAME_ID;
	}
	public static int defaultNumOfRounds = 1;
	public Weitergeben(Player[] player, Modus modus) {
		super(gameName, player, defaultNumOfRounds, modus);
	}
	@Override
	public String getShortInfo() {
		return shortInfo;
	}
	@Override
	public void nowVisible(){
		instance.changeBackground("media/nonPC/weitergeben/erbsen.jpg");
	}
}
