package games.difference;

import games.Modus;
import games.dialogeGUIs.GameSettingsDialog;

import java.awt.GridLayout;

import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.SwingConstants;


public class DifferenceSettingsDialog extends GameSettingsDialog {
	/**
	 * SerialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	private Difference dif;

	private JLabel rundenzahlLabel;

	private JSlider rundenzahlSlider;

	private JLabel zeitBisVerlorenLabel;

	private JSlider zeitBisVerlorenSlider;

	private JLabel bildVerschwindenLabel;

	private JCheckBox bildVerschwindenCheckBox;

	private GridLayout settingsPanelLayout;
	public DifferenceSettingsDialog(Difference dif) {
		super(dif);
		this.dif = dif;
		initGUI();
	}

	private void initGUI(){
		settingsPanelLayout = new GridLayout(2,2);
		settingsPanel.setLayout(settingsPanelLayout);
		rundenzahlLabel = new JLabel("Siegpunktzahl");
		settingsPanel.add(rundenzahlLabel);
		rundenzahlSlider = new JSlider(SwingConstants.HORIZONTAL,1,10,dif.numOfRounds);
		rundenzahlSlider.setMajorTickSpacing(1);
		rundenzahlSlider.setMinorTickSpacing(1);
		rundenzahlSlider.setSnapToTicks(true);
		rundenzahlSlider.setPaintTicks(true);
		rundenzahlSlider.setPaintLabels(true);
		settingsPanel.add(rundenzahlSlider);
		zeitBisVerlorenLabel = new JLabel("Zeit nach buzzern:");
		settingsPanel.add(zeitBisVerlorenLabel);
		if(dif.modus == Modus.SOLO){
			zeitBisVerlorenSlider = new JSlider(SwingConstants.HORIZONTAL,0,100,dif.getCdTime());
			zeitBisVerlorenSlider.setMajorTickSpacing(10);
		}
		else{
			zeitBisVerlorenSlider = new JSlider(SwingConstants.HORIZONTAL,3,15,dif.getCdTime());
			zeitBisVerlorenSlider.setMajorTickSpacing(1);
		}
		zeitBisVerlorenSlider.setMinorTickSpacing(1);
		zeitBisVerlorenSlider.setSnapToTicks(true);
		zeitBisVerlorenSlider.setPaintTicks(true);
		zeitBisVerlorenSlider.setPaintLabels(true);
		settingsPanel.add(zeitBisVerlorenSlider);
		if(dif.modus != Modus.SOLO){
			settingsPanelLayout.setRows(3);
			bildVerschwindenLabel = new JLabel("Bild nach buzzern ausblenden?");
			settingsPanel.add(bildVerschwindenLabel);
			bildVerschwindenCheckBox = new JCheckBox();
			bildVerschwindenCheckBox.setSelected(dif.bildAusblenden);
			settingsPanel.add(bildVerschwindenCheckBox);
		}
		
	}

	@Override
	public void speichern(){
		dif.numOfRounds = rundenzahlSlider.getValue();
		int zeit = zeitBisVerlorenSlider.getValue();
		if(zeit==0)zeit++;
		dif.setCdTime(zeit);
		if(dif.modus != Modus.SOLO)dif.bildAusblenden = bildVerschwindenCheckBox.isSelected();
		super.speichern();
	}
}
