package games.world;

import games.Modus;
import games.dialogeGUIs.GameSettingsDialog;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.SwingConstants;


public class WorldSettingsDialog extends GameSettingsDialog {
	/**
	 * SerialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	private World world;

	private JLabel rundenzahlLabel;

	private JSlider rundenzahlSlider;

	private JLabel toleranzLabel;

	private JSlider toleranzSlider;

	private JLabel toleranzOnLabel;

	private JCheckBox toleranzCheckBox;
	public WorldSettingsDialog(World world) {
		super(world);
		this.world = world;
		initGUI();
	}

	private void initGUI(){
		settingsPanel.setLayout(new GridLayout(3,2));
		rundenzahlLabel = new JLabel("Siegpunktzahl");
		settingsPanel.add(rundenzahlLabel);
		rundenzahlSlider = new JSlider(SwingConstants.HORIZONTAL,1,10,world.numOfRounds);
		rundenzahlSlider.setMajorTickSpacing(1);
		rundenzahlSlider.setMinorTickSpacing(1);
		rundenzahlSlider.setSnapToTicks(true);
		rundenzahlSlider.setPaintTicks(true);
		rundenzahlSlider.setPaintLabels(true);
		settingsPanel.add(rundenzahlSlider);
		{
			toleranzLabel = new JLabel();
			settingsPanel.add(toleranzLabel);
			toleranzLabel.setText("Toleranz in km");
		}
		{
			toleranzSlider = new JSlider(SwingConstants.HORIZONTAL,0,500,world.toleranz);
			toleranzSlider.setValue(world.toleranz);
			toleranzSlider.setMajorTickSpacing(100);
			toleranzSlider.setMinorTickSpacing(10);
			toleranzSlider.setSnapToTicks(true);
			toleranzSlider.setPaintTicks(true);
			toleranzSlider.setPaintLabels(true);
			toleranzSlider.setEnabled(world.toleranzOn);
			settingsPanel.add(toleranzSlider);
		}
		{
			toleranzOnLabel = new JLabel();
			settingsPanel.add(toleranzOnLabel);
			toleranzOnLabel.setText("Toleranz anschalten");
		}
		{
			toleranzCheckBox = new JCheckBox();
			toleranzCheckBox.setSelected(world.toleranzOn);
			settingsPanel.add(toleranzCheckBox);
			toleranzCheckBox.setText("Toleranz");
			if(world.modus == Modus.SOLO)toleranzCheckBox.setEnabled(false);
			toleranzCheckBox.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent evt) {
					toleranzCheckBoxActionPerformed(evt);
				}
			});
		}
	}
	
	private void toleranzCheckBoxActionPerformed(ActionEvent evt) {
		toleranzSlider.setEnabled(toleranzCheckBox.isSelected());
	}

	@Override
	public void speichern(){
		world.numOfRounds = rundenzahlSlider.getValue();
		world.toleranzOn = toleranzCheckBox.isSelected();
		world.toleranz = toleranzSlider.getValue();
		super.speichern();
	}
}
